// Copyright (c) FIRST and other WPILib contributors.
// Open Source Software; you can modify and/or share it under the terms of
// the WPILib BSD license file in the root directory of this project.

package frc.robot.subsystems;

import com.ctre.phoenix.ErrorCode;
import com.ctre.phoenix.led.CANdle;
import com.ctre.phoenix.led.CANdle.LEDStripType;
import com.ctre.phoenix.led.CANdleConfiguration;
import com.ctre.phoenix.led.CANdleFaults;
import com.ctre.phoenix.led.RainbowAnimation;

import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj2.command.SubsystemBase;


public class LEDSubsystem extends SubsystemBase {
  private CANdle candle = new CANdle(31);
  private CANdleConfiguration config = new CANdleConfiguration();
  /** Creates a new LEDSubsystem. */
  
  public LEDSubsystem() {
   
    
    config.v5Enabled=true;
    config.stripType = LEDStripType.RGB; // set the strip type to RGB
    config.brightnessScalar = 1.0; // dim the LEDs to half brightness
    candle.configAllSettings(config);
    
  }

  public void set(int R, int G, int B){
    //candle.setLEDs(R,G,B);
  
    candle.setLEDs(R, G, B, 0, 0, 14);
    //RainbowAnimation rainbowAnim = new RainbowAnimation(1, 0.5, 16);

    //candle.animate(rainbowAnim);
    
  } 


  
  @Override
  public void periodic() {
    // This method will be called once per scheduler run
    ErrorCode error = candle.getLastError(); // gets the last error generated by the CANdle

    CANdleFaults faults = new CANdleFaults();

    ErrorCode faultsError = candle.getFaults(faults);

    SmartDashboard.putString("Errors", error.toString());
    SmartDashboard.putString("Faults",faultsError.toString());
  }
}
